name: user_repository
description: Dart package which manages the user profile domain.
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.3.0
  equatable: ^2.0.3
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  firebase_storage_service: 
    path: ../firebase_storage_service
  flutter:
    sdk: flutter
  google_sign_in: ^5.2.1
  json_annotation: ^4.4.0
  sign_in_with_apple: ^3.3.0
  very_good_analysis: ^2.4.0
  

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.1
  mocktail: ^0.2.0
