name: analytics_repository
description: Package which manages the analytics domain.
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  firebase_analytics: ^9.0.4
  flutter:
    sdk: flutter
  very_good_analysis: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
