name: form_inputs
description: A Dart package which exposes reusable form inputs and validation rules
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  formz: ^0.4.1

dev_dependencies:
  test: ^1.19.5
  very_good_analysis: ^2.4.0
