name: firebase_storage_service
description: Dart package which manages the storage in Firebase storage.
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  firebase_auth: ^3.3.4
  firebase_storage: ^10.2.4
  very_good_analysis: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

